#!/bin/bash

# Originally written by Steven Brown
# http://www.stevenbrown.ca

# CUSTOMIZE START ####################################################
DATETIME="%Y.%m.%d-%H:%M:%S" # Date/Time output format
DEFAULT_SLEEPTIME=2
OUTFILE=`date +"%Y.%m.%d-%H.%M.%S"`
# CUSTOMIZE END ######################################################

print_usage_and_exit() {
    echo "Usage: $0 [interval]" >&2
    echo "       interval: the length in seconds between polls, default=$DEFAULT_SLEEPTIME" >&2
    exit 1
}

if [ $# -eq 0 ] ; then
    SLEEPTIME=$DEFAULT_SLEEPTIME
elif [ $# -eq 1 ] ; then
    
    # Test Interval, in seconds
    if ! [[ "$1" =~ ^[0-9]+$ ]] ; then 
	echo "Invalid interval '$1'" >&2
	print_usage_and_exit
    else
	SLEEPTIME=$1
    fi
else
    print_usage_and_exit
fi


# Begin ##############################################################
echo "# Wireless Strength at $SLEEPTIME second intervals."
echo "#   (Use ctrl-c to stop) " >&2
echo "# "`date +"%c"`

while true 
do
	s=`nm-tool | grep -e '^\s*\*'`
	# Now, s=something like:
	#    *networkid:     Infra, 00:13:46:1E:82:22, Freq 2437 MHz, Rate 54 Mb/s, Strength 100 WEP

	# Strip everything up to the number away, then get the number using awk
	s=${s/*[sS]trength /}
	s=`echo $s | awk '{print $1}'`

	# Get output to be a decimal, or zero
	output=`echo "scale=2;$s/100" | bc -l`

	echo -e `date +$DATETIME`"\t"$output
	echo -e `date +$DATETIME`"\t"$output >> "$OUTFILE.dat"
	sleep $SLEEPTIME

done

